// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Funkcije
    {
        public string Kategorija { get; set; }
        public int Id { get; set; }
        public string Naziv { get; set; }
        public int IdPodsustav { get; set; }

        public virtual Podsustav IdPodsustavNavigation { get; set; }
    }
}