// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Informacija
    {
        public Informacija()
        {
            PrimaInformaciju = new HashSet<PrimaInformaciju>();
        }

        public int Id { get; set; }
        public string Poruka { get; set; }
        public DateTime DatumSlanja { get; set; }
        public int IdUredaj { get; set; }

        public virtual Uredaj IdUredajNavigation { get; set; }
        public virtual ICollection<PrimaInformaciju> PrimaInformaciju { get; set; }
    }
}