// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class IzbioKvar
    {
        public int IdUredaj { get; set; }
        public int IdKvar { get; set; }

        public virtual Kvar IdKvarNavigation { get; set; }
        public virtual Uredaj IdUredajNavigation { get; set; }
    }
}