// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models
{
    public partial class Kontrolor
    {
        public Kontrolor()
        {
            NadzirePodsustav = new HashSet<NadzirePodsustav>();
            PrimaInformaciju = new HashSet<PrimaInformaciju>();
            RadniNalog = new HashSet<RadniNalog>();
        }

        public int Id { get; set; }
        [Display(Name = "Ime: ", Prompt = "Unesite ime kontrolora")]
        public string Ime { get; set; }
        [Display(Name = "Prezime: ", Prompt = "Unesite prezime kontrolora")]
        public string Prezime { get; set; }
        [Display(Name = "OIB: ", Prompt = "Unesite OIB kontrolora")]
        public string Oib { get; set; }
        [Display(Name = "Datum zaposlenja: ", Prompt = "Unesite datum zaposlenja")]
        public DateTime DatumZaposlenja { get; set; }
        [Display(Name = "Zaposlen do: ", Prompt = "Unesite datum isteka ugovora o zaposlenju")]
        public DateTime? ZaposlenDo { get; set; }
        [Display(Name = "Lozinka: ", Prompt = "Unesite lozinku")]
        public string Lozinka { get; set; }
        [Display(Name = "Korisničko ime: ", Prompt = "Unesite korisničko ime kontrolora")]
        public string KorisnickoIme { get; set; }
        [Display(Name = "Smjena: ", Prompt = "Unesite početak smjene")]
        public int IdSmjena { get; set; }
        [Display(Name = "Rang: ", Prompt = "Unesite rang kontrolora")]
        public int IdRang { get; set; }

        public virtual Rang IdRangNavigation { get; set; }
        public virtual Smjena IdSmjenaNavigation { get; set; }
        public virtual ICollection<NadzirePodsustav> NadzirePodsustav { get; set; }
        public virtual ICollection<PrimaInformaciju> PrimaInformaciju { get; set; }
        public virtual ICollection<RadniNalog> RadniNalog { get; set; }
    }
}