// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class KrajSmjene
    {
        public KrajSmjene()
        {
            Smjena = new HashSet<Smjena>();
        }

        public int Id { get; set; }
        public string VrijemeKrajaSmjene { get; set; }

        public virtual ICollection<Smjena> Smjena { get; set; }
    }
}