// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Kriticnost
    {
        public Kriticnost()
        {
            Podsustav = new HashSet<Podsustav>();
            Sustav = new HashSet<Sustav>();
        }

        public int Id { get; set; }
        public string StupanjKriticnosti { get; set; }

        public virtual ICollection<Podsustav> Podsustav { get; set; }
        public virtual ICollection<Sustav> Sustav { get; set; }
    }
}