// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Kvar
    {
        public Kvar()
        {
            IzbioKvar = new HashSet<IzbioKvar>();
            RadniNalog = new HashSet<RadniNalog>();
        }

        public int Id { get; set; }
        public string Tip { get; set; }
        public int Ozbiljnost { get; set; }
        public string Opis { get; set; }
        public int IdPrirucnik { get; set; }

        public virtual Prirucnik IdPrirucnikNavigation { get; set; }
        public virtual ICollection<IzbioKvar> IzbioKvar { get; set; }
        public virtual ICollection<RadniNalog> RadniNalog { get; set; }
    }
}