// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class NadleznoTijelo
    {
        public NadleznoTijelo()
        {
            IzdajePrirucnik = new HashSet<IzdajePrirucnik>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Tip { get; set; }

        public virtual ICollection<IzdajePrirucnik> IzdajePrirucnik { get; set; }
    }
}