// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class NoviKvar
    {
        public NoviKvar()
        {
            UnosiSeKvar = new HashSet<UnosiSeKvar>();
        }

        public int Id { get; set; }
        public string PostupakRjesavanja { get; set; }
        public string Tip { get; set; }
        public int Ozbiljnost { get; set; }
        public string Opis { get; set; }

        public virtual ICollection<UnosiSeKvar> UnosiSeKvar { get; set; }
    }
}