// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class PlaniranZa
    {
        public int IdLokacija { get; set; }
        public int IdPlanOdrzavanja { get; set; }

        public virtual Lokacija IdLokacijaNavigation { get; set; }
        public virtual PlanOdrzavanja IdPlanOdrzavanjaNavigation { get; set; }
    }
}