// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class PodrucjeRada
    {
        public PodrucjeRada()
        {
            TimZaOdrzavanje = new HashSet<TimZaOdrzavanje>();
        }

        public int Id { get; set; }
        public string VrstaPodrucjaRada { get; set; }

        public virtual ICollection<TimZaOdrzavanje> TimZaOdrzavanje { get; set; }
    }
}