// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Prioritet
    {
        public Prioritet()
        {
            RadniNalog = new HashSet<RadniNalog>();
        }

        public int Id { get; set; }
        public string StupanjPrioriteta { get; set; }

        public virtual ICollection<RadniNalog> RadniNalog { get; set; }
    }
}