// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Prirucnik
    {
        public Prirucnik()
        {
            IzdajePrirucnik = new HashSet<IzdajePrirucnik>();
            Kvar = new HashSet<Kvar>();
            Stavka = new HashSet<Stavka>();
            UnosiSeKvar = new HashSet<UnosiSeKvar>();
        }

        public int Id { get; set; }
        public string Izdavac { get; set; }
        public double Verzija { get; set; }
        public DateTime Datum { get; set; }
        public string Naziv { get; set; }
        public int IdUredaj { get; set; }

        public virtual Uredaj IdUredajNavigation { get; set; }
        public virtual ICollection<IzdajePrirucnik> IzdajePrirucnik { get; set; }
        public virtual ICollection<Kvar> Kvar { get; set; }
        public virtual ICollection<Stavka> Stavka { get; set; }
        public virtual ICollection<UnosiSeKvar> UnosiSeKvar { get; set; }
    }
}