// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Radnik
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Certifikat { get; set; }
        public DateTime? IstekCertifikata { get; set; }
        public int Dezuran { get; set; }
        public int IdTimZaOdrzavanje { get; set; }
        public int IdStrucnaSprema { get; set; }

        public virtual StrucnaSprema IdStrucnaSpremaNavigation { get; set; }
        public virtual TimZaOdrzavanje IdTimZaOdrzavanjeNavigation { get; set; }
    }
}