// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class RadniNalog
    {
        public RadniNalog()
        {
            RadniList = new HashSet<RadniList>();
        }

        public DateTime Sla { get; set; }
        public int Trajanje { get; set; }
        public string TipRada { get; set; }
        public string TragKvara { get; set; }
        public DateTime PocetakRada { get; set; }
        public int Id { get; set; }
        public int IdKontrolor { get; set; }
        public int IdVoditeljSmjene { get; set; }
        public int IdLokacija { get; set; }
        public int IdKvar { get; set; }
        public int IdStatus { get; set; }
        public int IdStupanjPrioriteta { get; set; }

        public virtual Kontrolor IdKontrolorNavigation { get; set; }
        public virtual Kvar IdKvarNavigation { get; set; }
        public virtual Lokacija IdLokacijaNavigation { get; set; }
        public virtual Status IdStatusNavigation { get; set; }
        public virtual Prioritet IdStupanjPrioritetaNavigation { get; set; }
        public virtual VoditeljSmjene IdVoditeljSmjeneNavigation { get; set; }
        public virtual ICollection<RadniList> RadniList { get; set; }
    }
}