// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Rang
    {
        public Rang()
        {
            Kontrolor = new HashSet<Kontrolor>();
        }

        public int Id { get; set; }
        public string ImeRanga { get; set; }

        public virtual ICollection<Kontrolor> Kontrolor { get; set; }
    }
}