// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Smjena
    {
        public Smjena()
        {
            Kontrolor = new HashSet<Kontrolor>();
            VoditeljSmjene = new HashSet<VoditeljSmjene>();
        }

        public int Id { get; set; }
        public string PocetakSmjene { get; set; }
        public double PlatniFaktor { get; set; }
        public int IdKrajSmjene { get; set; }

        public virtual KrajSmjene IdKrajSmjeneNavigation { get; set; }
        public virtual ICollection<Kontrolor> Kontrolor { get; set; }
        public virtual ICollection<VoditeljSmjene> VoditeljSmjene { get; set; }
    }
}