// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Stanje
    {
        public Stanje()
        {
            Uredaj = new HashSet<Uredaj>();
        }

        public int Id { get; set; }
        public string TipStanja { get; set; }

        public virtual ICollection<Uredaj> Uredaj { get; set; }
    }
}