// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Sustav
    {
        public Sustav()
        {
            Podsustav = new HashSet<Podsustav>();
        }

        public int Id { get; set; }
        public int Osjetljivost { get; set; }
        public string Opis { get; set; }
        public int IdKriticnost { get; set; }
        public int IdVrstaSustava { get; set; }

        public virtual Kriticnost IdKriticnostNavigation { get; set; }
        public virtual VrstaSustava IdVrstaSustavaNavigation { get; set; }
        public virtual ICollection<Podsustav> Podsustav { get; set; }
    }
}