// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class SystemLogging
    {
        public Guid SystemLoggingGuid { get; set; }
        public DateTime? EnteredDate { get; set; }
        public string LogApplication { get; set; }
        public string LogDate { get; set; }
        public string LogLevel { get; set; }
        public string LogLogger { get; set; }
        public string LogMessage { get; set; }
        public string LogMachineName { get; set; }
        public string LogUserName { get; set; }
        public string LogCallSite { get; set; }
        public string LogThread { get; set; }
        public string LogException { get; set; }
        public string LogStacktrace { get; set; }
    }
}