// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class TimZaOdrzavanje
    {
        public TimZaOdrzavanje()
        {
            PlanOdrzavanja = new HashSet<PlanOdrzavanja>();
            RadniList = new HashSet<RadniList>();
            Radnik = new HashSet<Radnik>();
        }

        public int Id { get; set; }
        public DateTime DatumOsnivanja { get; set; }
        public string NazivTima { get; set; }
        public int Satnica { get; set; }
        public int IdPodrucjeRada { get; set; }

        public virtual PodrucjeRada IdPodrucjeRadaNavigation { get; set; }
        public virtual ICollection<PlanOdrzavanja> PlanOdrzavanja { get; set; }
        public virtual ICollection<RadniList> RadniList { get; set; }
        public virtual ICollection<Radnik> Radnik { get; set; }
    }
}