// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class TipOpreme
    {
        public TipOpreme()
        {
            Oprema = new HashSet<Oprema>();
        }

        public int Id { get; set; }
        public string TipOpreme1 { get; set; }

        public virtual ICollection<Oprema> Oprema { get; set; }
    }
}