// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class UnosiSeKvar
    {
        public int IdPrirucnik { get; set; }
        public int IdNoviKvar { get; set; }

        public virtual NoviKvar IdNoviKvarNavigation { get; set; }
        public virtual Prirucnik IdPrirucnikNavigation { get; set; }
    }
}