// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Uredaj
    {
        public Uredaj()
        {
            Informacija = new HashSet<Informacija>();
            IzbioKvar = new HashSet<IzbioKvar>();
            Prirucnik = new HashSet<Prirucnik>();
            RadniList = new HashSet<RadniList>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Proizvodac { get; set; }
        public string GodinaProizvodnje { get; set; }
        public int IdOprema { get; set; }
        public int IdStanje { get; set; }

        public virtual Oprema IdOpremaNavigation { get; set; }
        public virtual Stanje IdStanjeNavigation { get; set; }
        public virtual ICollection<Informacija> Informacija { get; set; }
        public virtual ICollection<IzbioKvar> IzbioKvar { get; set; }
        public virtual ICollection<Prirucnik> Prirucnik { get; set; }
        public virtual ICollection<RadniList> RadniList { get; set; }
    }
}