// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class VoditeljSmjene
    {
        public VoditeljSmjene()
        {
            RadniNalog = new HashSet<RadniNalog>();
        }

        public int Id { get; set; }
        public int IdSmjena { get; set; }

        public virtual Smjena IdSmjenaNavigation { get; set; }
        public virtual ICollection<RadniNalog> RadniNalog { get; set; }
    }
}